# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.camera_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.camera_label_1.setGeometry(QtCore.QRect(130, 50, 370, 340))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.camera_label_1.setFont(font)
        self.camera_label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camera_label_1.setObjectName("camera_label_1")
        self.OP_Button = QtWidgets.QPushButton(self.centralwidget)
        self.OP_Button.setGeometry(QtCore.QRect(1220, 390, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.OP_Button.setFont(font)
        self.OP_Button.setObjectName("OP_Button")
        self.exit_Button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_Button.setGeometry(QtCore.QRect(1220, 610, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.exit_Button.setFont(font)
        self.exit_Button.setObjectName("exit_Button")
        self.result_label_1 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_1.setGeometry(QtCore.QRect(130, 410, 370, 70))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.result_label_1.setFont(font)
        self.result_label_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result_label_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.result_label_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_label_1.setTextFormat(QtCore.Qt.AutoText)
        self.result_label_1.setObjectName("result_label_1")
        self.camera_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.camera_label_2.setGeometry(QtCore.QRect(530, 50, 370, 340))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.camera_label_2.setFont(font)
        self.camera_label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camera_label_2.setObjectName("camera_label_2")
        self.camera_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.camera_label_3.setGeometry(QtCore.QRect(130, 520, 370, 340))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.camera_label_3.setFont(font)
        self.camera_label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camera_label_3.setObjectName("camera_label_3")
        self.camera_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.camera_label_4.setGeometry(QtCore.QRect(530, 520, 370, 340))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.camera_label_4.setFont(font)
        self.camera_label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.camera_label_4.setObjectName("camera_label_4")
        self.SR_Button = QtWidgets.QPushButton(self.centralwidget)
        self.SR_Button.setGeometry(QtCore.QRect(1220, 500, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.SR_Button.setFont(font)
        self.SR_Button.setObjectName("SR_Button")
        self.result_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_2.setGeometry(QtCore.QRect(530, 410, 370, 70))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.result_label_2.setFont(font)
        self.result_label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result_label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.result_label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_label_2.setTextFormat(QtCore.Qt.AutoText)
        self.result_label_2.setObjectName("result_label_2")
        self.result_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_3.setGeometry(QtCore.QRect(130, 880, 370, 70))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.result_label_3.setFont(font)
        self.result_label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result_label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.result_label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_label_3.setTextFormat(QtCore.Qt.AutoText)
        self.result_label_3.setObjectName("result_label_3")
        self.result_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.result_label_4.setGeometry(QtCore.QRect(530, 880, 370, 70))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.result_label_4.setFont(font)
        self.result_label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result_label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.result_label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_label_4.setTextFormat(QtCore.Qt.AutoText)
        self.result_label_4.setObjectName("result_label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.camera_label_1.setText(_translate("MainWindow", "camera page"))
        self.OP_Button.setText(_translate("MainWindow", "open camera"))
        self.exit_Button.setText(_translate("MainWindow", "exit"))
        self.result_label_1.setText(_translate("MainWindow", "Result is:"))
        self.camera_label_2.setText(_translate("MainWindow", "camera page"))
        self.camera_label_3.setText(_translate("MainWindow", "camera page"))
        self.camera_label_4.setText(_translate("MainWindow", "camera page"))
        self.SR_Button.setText(_translate("MainWindow", "start recognition"))
        self.result_label_2.setText(_translate("MainWindow", "Result is:"))
        self.result_label_3.setText(_translate("MainWindow", "Result is:"))
        self.result_label_4.setText(_translate("MainWindow", "Result is:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
